### ISSUE TITLE
OpenSL ES sink

### ISSUE THREAD

**Issue by twaik** [glance-/pulseaudio-android-ndk#4]
Hi! I have working OpenSL ES sink [code](https://gist.github.com/twaik/0eaee765c712ddd03fc9dc4eaac09cfc), but it needs to be tested and improved. Can you help me with testing?

**Comment by glance-** [comment]
There is quite some manual work to test it for real, but i can try to get time to it.

**Comment by glance-** [comment]
Woo. I finally got around to testing your code and it works.

I had this running in a emulator, piping the sound from my desktop into the emulator and out via the emulator soundcard again.

Now, I just need to wrap this in a android app which can start it.

**Comment by twaik** [comment]
Termux has both sink (this modified source) and source (mic)
