### ISSUE TITLE
Building for x86 and x86_64

### ISSUE THREAD

**Issue by shakthi-prashanth-m** [glance-/pulseaudio-android-ndk#5]
Hi,

I want to build pulseaudio for Android x86/x86_64. Can you please provide steps ?
Thanks in advance.

Regards,
Shakthi

**Comment by glance-** [comment]
download the andoid ndk and run the build-script with the argument of the argument you would like to build for.

This is not a end user friendly tool, rather a engineering tool for producing binaries to use in other projects.

**Comment by shakthi-prashanth-m** [comment]
Hi @glance-  thanks for your input. I built pulseaudio successfully. Libraries were generated in ~/pulseaudio-android-ndk/pulseaudio-build-x86_64/src/.libs
```
./src/.libs/libpulsecommon-12.99.so
./src/.libs/libpulsecore-12.99.so
./src/.libs/libpulse-simple.so
./src/.libs/libpulse.so
```
However, I wanted to use them in the Android build for linking them to https://github.com/alsa-project/alsa-plugins/tree/master/pulse. But I get below error:

`libasound_module_pcm_pulse (SHARED_LIBRARIES android-x86_64) missing libpulse (SHARED_LIBRARIES android-x86_64) 
`

Can you please help how can I link use pulseaudio client libraries to built alsa-plugins, so that I can use it in aplay command in Android.

For eg: below command should work in Android:
`aplay -D pulse audio.wav`

Your help is really appreciated.
